FROM mysql:8

#RUN /etc/init.d/mysql start
#RUN mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE 3gis"

#COPY create-schema.sql /docker-entrypoint-initdb.d/
#CMD ["mysqld", "--init-file=/tmp/create-schema.sql"]

